### ISSUE TITLE
[Using Sessions][secsin]  -  cryptic reference

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/sinatra-mechanics-of-sessions-readme#15]
Two cryptic references in this lesson without links or explanation, googling returns this same Learn.co page. Are these placeholders someone forgot to fill in?

"This is covered in [their documentation][secsin]."
"[Using Sessions][secsin]"

**Comment by Sdcrouse** [comment]
I wondered about that, too. My guess is that they meant to link to [http://sinatrarb.com/intro.html](http://sinatrarb.com/intro.html), and then have you scroll down to the "Session Secret Security" section (man, what a tongue twister).

Hope that helps!

Sdcrouse
